### ISSUE TITLE
[Bug]: Incorrect Page Saving

### ISSUE THREAD

**Issue by DeerFee** [ollm/OpenComic#287] opened 2024-10-31 12:25 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.3.1

### Operating System

Windows 10 Pro 22H2

### Installed via

.exe installer

### Steps to reproduce

1. Open the comic (preferably in ZIP format).
2. Save the first page.
3. Check the location where you saved it.

### Expected Behavior

You will get the first page (preferably with a new creation date).

### Actual Behavior

Instead, you get the last page (and with the old date).

### Error message

No

### Additional Information

When I select page 001 to save, it somehow saves page 059 (the last one). Also, is there a way to set a new date for the saved file? Currently, it keeps the date that belongs to the original file from the archive.

**Comment by ollm** [comment] 2024-11-08 15:38
Thanks for reporting!

It seams a duplicate of https://github.com/ollm/OpenComic/issues/285, I fixed this in b14a26eacdc77d37cdeb578fc203438058c7c5e2, you can try the following master build.

Build: https://mega.nz/file/bXRFFQYb#M6MEKO-EY0W5BebAAeTFH4lsgFwBbcRoW4WlJ6sK1I8

**Closed** 2024-11-08 15:44 UTC
Labels: bug, duplicate, ready to ship 🚀
