### ISSUE TITLE
unable to open .cbz file

### ISSUE THREAD

**Issue by AbhishekKhandelwal** [ollm/OpenComic#101] opened 2021-05-16 12:13 UTC
A few days ago it was working perfectly but yesterday it was not working.
![Screenshot (4)](https://user-images.githubusercontent.com/10695723/118396914-665f1880-b671-11eb-8d8e-9071820713a7.png)

**Comment by ollm** [comment] 2021-05-16 12:37
It looks like a duplicate of https://github.com/ollm/OpenComic/issues/62

You can try this version, it should have the problem fixed: https://mega.nz/file/nGxFBQoS#DiIHAUxp5SSBvz742TnXqSD0KXeWqJ46e3ege0y9ghw

**Closed** 2023-10-09 15:36 UTC
Labels: bug
