### ISSUE TITLE
[Bug]: scroll jump in fullscreen

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#229] opened 2024-05-15 13:45 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

I reported somewhere this bug some time ago, but can't find where. So can't leave "related".
1. Open webtoon/manga
2. F11
3. Scroll to somewhere
4. Alt+tab
5. Alt+tab back

<details>
<summary>Screen record</summary>

https://github.com/ollm/OpenComic/assets/96221151/7bfb00ba-90d3-4336-b6c8-b8805ba4b0e6

</details>

### Expected Behavior

Nothing changes.

### Actual Behavior

Sometime scroll jump to some fixed position. For example, if I say that first fixed position is 0, then I can scroll let's say 3 lines, it will jump to 0. 5 lines it will jump to 0, but scroll 8 lines will jump to next fixed position on 10 line.
Bug is not consistent (can have this bug one day, but not other), but pretty frequent.

Probably related info:
1. Maybe horizontal margin make things worse a bit (bigger jump size). I noticed this bug first time when I used horizontal margin for hi-quality manga (3000px+ width size of pages)
2. Usually bug shows for the first time when you open chapter. If I exit to library and then again open same chapter it's pretty hard to reproduce this bug again.

**Comment by ollm** [comment] 2024-05-16 09:07
I have been able to reproduce the bug a few times, after making these changes e12383a488fa22faea5498fce95a3d4882639795 it has not appeared again, although since it is an inconsistent bug, I am not entirely sure that it has been solved.

I also fix the "next chapter" bug reported here https://github.com/ollm/OpenComic/issues/230 b0134318064b43e2fb11d5f9303cd025603ebe1a

Build: https://mega.nz/file/vLJA1IJb#HEoO5GoXy6KiBCQB3jRWHtavhAEt6xU5oNLMgWFVXzM

- Scroll jump in fullscreen using alt+tab (Windows) e12383a488fa22faea5498fce95a3d4882639795
- Errors when fast pressing shortcuts keys when reading is loading b0134318064b43e2fb11d5f9303cd025603ebe1a

**Comment by dajotim937** [comment] 2024-05-18 20:44
> I am not entirely sure that it has been solved

Well, looks like like it's mostly fixed. It doesn't jump like it was and I only got one random jump and couldn't reproduce. There is small movements sometimes, but it doesn't bother if you don't specifically look for them.

**Comment by ollm** [comment] 2024-05-19 09:40
I have been testing a little more and so far it has only appeared after changing the margin values, I have made some changes to fix in this case and also the small movements bf0946e652a9ddf723a69a679fd87d8016dd9ad8

Build: https://mega.nz/file/vTgjwK5K#cZByTcMcJzn7-h5GHnmlL4niJ157Wo-uHV0XwBRxl4c

**Comment by dajotim937** [comment] 2024-06-02 18:12
Finally tested a bit and yeah, looks like fixed now.

**Comment by ollm** [comment] 2024-10-04 18:57
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)

**Closed by ollm** 2024-10-04 18:57 UTC
Labels: bug, ready to ship 🚀
