### ISSUE TITLE
menu is not showing

### ISSUE THREAD

**Issue by Grimstonsd** [ollm/OpenComic#54] opened 2020-09-15 01:53 UTC
![Captura de Tela (1)](https://user-images.githubusercontent.com/71301565/93155702-0f1d3880-f6dd-11ea-9c09-0abc855386a9.png)

**Comment by ollm** [comment] 2020-09-16 16:33
Try this version, I have added a dialog that should show the error in case the development tools cannot be accessed.

https://mega.nz/file/HOJRkIwA#Kc0xyaKgmdXz33WH6An43X30yamlXgnBfpTkSWUw-Zc

**Comment by Grimstonsd** [comment] 2020-09-20 18:38
now this error appears
![Captura de Tela (1)](https://user-images.githubusercontent.com/71301565/93719183-3e0d3180-fb57-11ea-9224-c1ebd18f01a0.png)

**Comment by ollm** [comment] 2020-09-21 13:41
Fixed in d5c3d1722535ada487d1cb99c0c85781c04cadb5 and 3785bec6bdeb0d71584e185a5cdf7340c944fd67

The error was caused by an incorrect path to the language file.

Here is the version with the problem fixed: 

https://mega.nz/file/XLpkFAya#OO8sQVlzmAZJsRHzuvabaBBTI6-OQCn4EeYjXwgVhc0

**Closed by ollm** 2020-09-21 13:41 UTC
Labels: bug
