### ISSUE TITLE
OpenComic is unable to handle file names with special characters well

### ISSUE THREAD

**Issue by minhngoc25a** [ollm/OpenComic#150] opened 2022-12-28 04:43 UTC
I have a CBZ file located in the following path:

"E:\[Glitter] One Piece - Digital Colored Comics (+ Cover Stories)\One Piece - Digital Colored Comics v099 (anonymous).cbz"

And when I try to open it, the program throws the following error:

![image](https://user-images.githubusercontent.com/33834488/209758532-65d7c0d9-42db-43e1-9e2c-8a76b43a07c2.png)

I think it is something to do with the pluses or the square brackets in the file name. It would be nice to get this fixed.

**Comment by ollm** [comment] 2022-12-28 10:13
Duplicate of #101 #138

**Closed by ollm** 2022-12-28 10:13 UTC
