### ISSUE TITLE
PDF Image Quality Is Very Poor

### ISSUE THREAD

**Issue by SegaKawaii** [ollm/OpenComic#104] opened 2021-06-17 16:31 UTC
When viewing PDF files in OpenComic, the image quality seems to be significantly worse than other readers. This makes text very blurry and smaller text can become completely illegible. While larger text is usually fine, this make reading furigana nearly impossible. I could not find any settings to adjust this.

Example image from a magazine:
![Screenshot from 2021-06-17 11-20-39](https://user-images.githubusercontent.com/43504591/122436898-d1e12200-cf5e-11eb-9f5d-0ac75f4203cf.png)

Here is the same exact file at a similar zoom, but in the Evince Document Viewer:
![Screenshot from 2021-06-17 11-21-50](https://user-images.githubusercontent.com/43504591/122436942-db6a8a00-cf5e-11eb-9c8f-9ac9d20dbb0a.png)

**Comment by paconaranjo** [comment] 2021-08-29 22:21
I think they solved it here:
https://github.com/ollm/OpenComic/issues/109#issuecomment-907779839

**Comment by ollm** [comment] 2021-08-30 09:11
This is a different problem, currently the pages of a PDF are converted into JPG with the resolution of the PDF viewport, the problem is that this viewport often has a lower resolution than the images inside the PDF making them look blurry, to correct this problem I have to change the way OpenComic processes PDFs, I have to use the current display size instead of the PDF viewport.

I'll try to do it when I have a little time.

**Comment by ollm** [comment] 2023-08-22 13:42
Closed as completed in a55312d0ba46c9773b405f6528bd0b4f055e17b9 and available in [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.

**Closed by ollm** 2023-08-22 13:42 UTC
Labels: bug
