### ISSUE TITLE
PDF doesnt open

### ISSUE THREAD

**Issue by pr0fish** [ollm/OpenComic#157] opened 2023-05-05 10:23 UTC
for a while now i have been unable to view pdf's through opencomic- is there something I am missing?

https://imgur.com/a/nkG9Am5

**Comment by ollm** [comment] 2023-05-07 09:49
Can you confirm if you also have this bug in the beta version?

https://github.com/ollm/OpenComic/releases/tag/v0.2.2-beta3

**Comment by aorin1** [comment] 2023-07-19 13:09
It 

> Can you confirm if you also have this bug in the beta version?
> 
> https://github.com/ollm/OpenComic/releases/tag/v0.2.2-beta3

It does happen in the latest Beta as well, it doesn't open the PDF and shows the error from the user above. It also doesn't show the thumbnails for PDF files in the library.

**Comment by ollm** [comment] 2023-07-20 13:21
Can you send me the PDF you are testing? For my part, I have tried some PDFs in Windows 11 and I do not get any errors when opening them.

You can send it to my email if you prefer: [oleguer.llopart.mora@gmail.com](mailto:oleguer.llopart.mora@gmail.com)

**Comment by ollm** [comment] 2023-07-20 19:47
Thanks for sending the sample PDF, I have found the cause of the bug and sent a fix e24fb9f, the bug occurred when OpenComic start to unzip to generate the thumbnails and at the same time you try to open it, by mistake the same file was unzipped 2 times giving the error in the last, this normally only happened the first time this file appears in the library, since after being unzip once OpenComic keeps the list of files in cache and will only be unzip again when trying to read.

I have to improve the opening of PDF files, since the way it is currently implemented takes a long time to open them, apart from having some other problems https://github.com/ollm/OpenComic/issues/104

Version **0.2.2-beta4** with the fix: https://mega.nz/file/6WAWTYiJ#wKRv21V_kqvaemJXWsMc8IOwlTrPR-Fm66Yst9VxWzw

**Comment by aorin1** [comment] 2023-07-20 22:17
I've tried the beta4 release from the link above and it didn't return the error, the application is opening the PDF files and I appreciate that you're going to improve PDF support.
This is going to be my reader of choice for PDF, CBZ and even ePUB files if that is planned in the future.
Let me know how I can be of further assistance.

**Comment by ollm** [comment] 2023-08-22 13:47
Closed as completed in a55312d0ba46c9773b405f6528bd0b4f055e17b9 and available in [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.

**Closed by ollm** 2023-08-22 13:47 UTC
Labels: bug
