### ISSUE TITLE
[Bug]: Ctrl+ Scroll wheel didn't work correctly

### ISSUE THREAD

**Issue by mintrit29** [ollm/OpenComic#223] opened 2024-04-28 05:13 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

windows 11

### Steps to reproduce

Uploading bandicam 2024-04-28 12-06-54-896.mp4…

### Expected Behavior

I want that when i zoom in on the picture it will not have the bug like my attached video

### Actual Behavior

when I zoom on the picture it not only zooms in but also is a bug and cannot be normal

**Comment by ollm** [comment] 2024-04-28 07:50
Thanks for the bug report, could you attach the video again? It has not been uploaded correctly.

**Comment by mintrit29** [comment] 2024-04-28 14:10
https://github.com/ollm/OpenComic/assets/128055950/79266a0b-6126-4daa-ba08-ab9538f01493

Sure. Thank you for responding. Here is my new attach

**Comment by ollm** [comment] 2024-04-28 15:00
Can you check if this build has fixed the issue?

Build: https://mega.nz/file/CDRljQhS#ZQIEnAKtgJ0DXu2ow5Wo-ctHNKshudmQg2naWCL6Mes

If you still have it, can you check if there are any errors in the console? (Debug > DevTools)

Also, what reading preferences are you using? You can send me screenshots of the settings page and the reading menu.

**Comment by mintrit29** [comment] 2024-04-28 15:17
The link you gave me just had the same issue
![Screenshot 2024-04-28 221143](https://github.com/ollm/OpenComic/assets/128055950/15b71877-278f-478d-96ae-3a83e159eeb1)
![Screenshot 2024-04-28 221201](https://github.com/ollm/OpenComic/assets/128055950/452fc131-a84d-4706-b8a8-41390e55fe27)
![image](https://github.com/ollm/OpenComic/assets/128055950/746ff418-4040-4e34-a682-cd7534ab1d17)

I do not change much in the setting here are my screenshots

**Comment by ollm** [comment] 2024-04-28 18:28
At the moment I cannot reproduce the issue. Can you test if disabling the Interpolation method stops it happening? Settings > Interpolation Method > Disabled (Chromium) in both.

**Comment by mintrit29** [comment] 2024-04-29 04:32
It did not work.

**Comment by mintrit29** [comment] 2024-04-29 04:37
https://github.com/ollm/OpenComic/assets/128055950/592c0952-2815-4138-9561-de928fb8b1e7

I tried downloading the release version and not setting anything but still not working

**Comment by ollm** [comment] 2024-04-29 08:37
You can try and record the steps in the following video, from the behavior it seems that some of the transformations involved do not work correctly.

https://github.com/ollm/OpenComic/assets/18549191/f8f1189a-a09e-44ae-bd16-b6de9abd0db8

By the way, what scale are you using on your monitor? There have previously been some bugs in the app related to it https://github.com/ollm/OpenComic/issues/144#issuecomment-1894222027

![Captura de pantalla 2024-01-19 152147](https://github.com/ollm/OpenComic/assets/18549191/59cbb704-2109-45f6-a594-c627448fe497)

**Comment by mintrit29** [comment] 2024-04-30 06:08
https://github.com/ollm/OpenComic/assets/128055950/dfd9449d-48a8-44d8-b1c1-1869408872f9

**Comment by ollm** [comment] 2024-04-30 08:27
Finally I was able to reproduce the issue, it only happened with PDF files when the monitor scale was greater than 100% d318cfc071b5e8d919b4c8acef89b85e8ef40cc8

Build with the fix: https://mega.nz/file/fGoXRQ6T#wOXC_eu58p0SDaKUaurO1Mv0k0vpxN1kBWUTna_IYG0

**Comment by mintrit29** [comment] 2024-04-30 09:35
OMG Thank you so much!!

**Comment by Quest79** [comment] 2024-06-27 23:49
Can confirm, this bug was fixed. There is a bit of UI twitching a lot but I can make another bug report when i get a chance to capture it. This is usable now!

**Comment by ollm** [comment] 2024-10-04 18:57
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)

**Closed by ollm** 2024-10-04 18:57 UTC
Labels: bug, ready to ship 🚀
