### ISSUE TITLE
[Bug]: sometimes pages are blank

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#193] opened 2024-01-17 22:27 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

Can't figure out what cause of blank pages. Got this bug 3 times on 3 different files. After file reload or app restart -- image loads fine.

### Expected Behavior

Loaded image

### Actual Behavior

Blank page

### Additional Information

<details>
<summary>Screen record</summary>

https://github.com/ollm/OpenComic/assets/96221151/e7d0194a-0d46-4353-a57a-640846bdc904

</details>

**Comment by ollm** [comment] 2024-01-18 17:04
If it happens again, you can check for any error in DevTools (Debbug > Toogle DevTools)

Also you can try temporarily disabling the interpolation method, this was introduced in v1.1.0 and could be related

![Captura desde 2024-01-18 18-01-25](https://github.com/ollm/OpenComic/assets/18549191/cea19b73-5881-4211-a39e-9113464e2805)

**Comment by dajotim937** [comment] 2024-01-19 03:57
Those pic should be in original size without any interpolation, consider their size. Okay, I'll comment if got the bug again.

**Comment by gdhorner** [comment] 2024-05-17 15:24
Hi, I just downloaded OpenComic and am receiving this issue on every page I try to view. I have Bleach comics downloaded and all of them appear as blank pages but have no issue with other cbz viewers. I tried disabling the interpolation but doesn't seem to be fixed. I downloaded a single One Piece cbz to see if maybe my files were bad, but am also seeing the same on most pages of the One Piece chapter. It looks like it is just saying the file is not found for each jpg page. Unfortunately can't attach a cbz but here is a link to the One Piece [file](https://nyaa.si/view/1477998).
![image](https://github.com/ollm/OpenComic/assets/50218709/cf284bc1-c942-47db-99d7-7805bca74d61)

This is what every page looks like:
![image](https://github.com/ollm/OpenComic/assets/50218709/d5da92c9-86ef-435e-8c59-992814086559)

**Comment by dajotim937** [comment] 2024-05-17 19:04
Win10 with test build from https://github.com/ollm/OpenComic/issues/229#issuecomment-2114620367
Can't reproduce.
![image](https://github.com/ollm/OpenComic/assets/96221151/dbaef66d-59ec-472c-80e5-d6b564bfe521)

**Comment by ollm** [comment] 2024-05-18 08:24
I have downloaded the example file and it appears that the error is caused by not reading correctly the UTF8 characters in the file names when using 7zip, fix 27c863b6a9abd434e8855216100e5f8087ed1e73

Build with fix: https://mega.nz/file/rWhXjI5Q#GzGZRSkbUxvhnBB6Rt3JfZs8p_O8nVKQoFcRvybniyc

Once this build is installed, you will need to delete cache and temporary files from settings, as these would still have in cache the wrong file names from the previous build.

**Comment by gdhorner** [comment] 2024-05-18 12:45
Amazing, works like a charm! Thanks so much for the quick turnaround! :)

**Comment by himouto** [comment] 2024-06-21 03:21
> I have downloaded the example file and it appears that the error is caused by not reading correctly the UTF8 characters in the file names when using 7zip, fix [27c863b](https://github.com/ollm/OpenComic/commit/27c863b6a9abd434e8855216100e5f8087ed1e73)
> 
> Build with fix: https://mega.nz/file/rWhXjI5Q#GzGZRSkbUxvhnBB6Rt3JfZs8p_O8nVKQoFcRvybniyc
> 
> Once this build is installed, you will need to delete cache and temporary files from settings, as these would still have in cache the wrong file names from the previous build.

Having the same issue but only with cbz files with really long filenames. Temporary fix is to rename and shorten the filenames of the folders inside the cbz (zip) files but it's not really a long term solution since it ruins my properly tagged and catalogued manga collection.

**Comment by ollm** [comment] 2024-10-04 18:55
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)

**Closed by ollm** 2024-10-04 18:55 UTC
Labels: bug, ready to ship 🚀
