### ISSUE TITLE
[Bug]: error with cbz file  

### ISSUE THREAD

**Issue by ward333611** [ollm/OpenComic#267] opened 2024-09-11 11:14 UTC
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

win 11

### Steps to reproduce

error when open cbz file  

### Expected Behavior

![Untitled](https://github.com/user-attachments/assets/4d515a88-6182-4e63-ac86-16f1cdb5ea9d)

### Actual Behavior

error when open cbz file

**Comment by ollm** [comment] 2024-09-25 13:48
Although I'm not 100% sure, I think this happens when OpenComic extract the same image from different parts of the app at the same time, for example when reading and generating thumbnails.

I've made some changes that prevent this, so if this was the cause it should be fixed 98de35047700ba973e416c6b1540ccde51bdd7b0

You may need to delete the cache, as error messages are sometimes saved here to show them again.

Build: https://mega.nz/file/WPxXQYaC#fpDIv1iisNnf-o05ryoAl8Q0wyB2gM_-UtP9vGm2cAQ

**Comment by ollm** [comment] 2024-10-04 19:02
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)

**Closed by ollm** 2024-10-04 19:02 UTC
Labels: bug
